[plugins]
android-library = { id = "com.android.library", version = "7.5.0" }
download = { id = "com.github.ben-manes.versions", version = "0.42.0" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version = "1.8.10" }
